Add avatar component by Docux
DocusaurusCommunity/website pull request #29
Opened 2024-06-04 22:41 UTC by Juniors017

2024-07-21 19:28 UTC, homotechsual requested changes

2024-07-21 19:28 UTC, homotechsual commented on docs/component-library/new/Simplecard/index.mdx
>  </TabItem>
Why is this editing a file in `SimpleCard`?

2024-07-21 19:28 UTC, homotechsual commented on src/components/Avatar/AvatarContainer/index.tsx
> +
```suggestion
```

2024-07-21 19:28 UTC, homotechsual commented on src/components/Avatar/AvatarContainer/index.tsx
> +
```suggestion
```

2024-07-21 19:28 UTC, homotechsual commented on src/components/Avatar/AvatarImage/index.tsx
> +
```suggestion
```

2024-07-21 19:28 UTC, homotechsual commented on src/components/Avatar/AvatarImage/index.tsx
> +      )}
```suggestion
      className={clsx(
          "avatar__photo", 
          className, 
          avatarImageSizeClass
      )}
```

2024-07-21 19:28 UTC, homotechsual commented on src/components/Avatar/AvatarImage/index.tsx
> +
```suggestion
```

2024-07-22 16:31 UTC, Juniors017 commented
Hi @homotechsual 
I don t know why card componant was modificated.. it s old 😔
Sorry

2024-07-22 16:32 UTC, Juniors017 reviewed
Ok

2024-07-23 15:05 UTC, homotechsual commented
Sorry but this now deletes the SimpleCard file rather than leaving it unchanged. This would break the SimpleCard demo/example.

2024-07-28 21:25 UTC, closed without merging